### ISSUE TITLE
Card UI is appearing too small on Mobile

### ISSUE THREAD

**Issue by 0xhodler** [Up-Heal-DAO/up-heal-landing-page#34]
When on mobile the UI of the card is really hard to read, we want to have bigger cards and bigger text to make it more user-friendly.

Actual design 
<img width="377" alt="Screenshot 2022-05-07 at 13 09 40" src="https://user-images.githubusercontent.com/102098836/167251735-cd04f10f-1a9d-409b-adbe-84b1cec930e0.png">
on mobile:

**Comment by landiehan** [comment]
Hi, @yannieth. The hero section is set to a fixed width of 751px, which will cause the page layout width stay 751px on narrow device, in this case `max-width` is more suitable, and after switching to this property, the card section will look as good as on desktop, because the `initial-scale=1` is not set, the viewport will scale down to fit the fixed width, which makes the card section looks small.

**Comment by yannieth** [comment]
@landiehan Sound good!

**Comment by landiehan** [comment]
The PR #35  will automatically solve this issue.
